name: Deploy project at server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Node Js Configuration
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependences
        run: npm ci

      - name: Generate 11ty static site
        run: npm run build

      - name: Upload dist/ folder to FTP hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}